require('plugins-setup')
require('core.options')
require('core.keymaps')
require('core.colorscheme')

require('plugins.nvim-treesitter')
require('plugins.nvim-cmp')
require('plugins.comment')
require('plugins.nvim-tree')
require('plugins.orgmode')
